name: CI-Main Pipeline

on:
  pull_request:
    branches:
      - 'main'

jobs:
  ci:
    name: Run CI Pipeline
    uses: ./.github/workflows/ci-reusable.yml
    secrets: inherit
    with:
      python-version: '3.12'
