name: CI-PR Pipeline

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          
  ci:
    name: Run CI Pipeline
    uses: ./.github/workflows/ci-reusable.yml
    secrets: inherit
    with:
      python-version: '3.12'
